// GENERATED by tools/gen_structs.py - do not edit.
// ignore_for_file: non_constant_identifier_names
import 'dart:ffi';

final class TcConfig extends Struct {
  @Int64() external int market;
  @Int64() external int direction;
  @Int64() external int initial_barrier;
  @Int64() external int recovery_barrier1;
  @Int64() external int recovery_barrier2;
  @Int64() external int trigger_digit;
  @Int64() external int consecutive_count;
  @Int64() external int deviation_direction;
  @Int64() external int martingale_enabled;
  @Int64() external int martingale_max_steps;
  @Int64() external int max_consecutive_losses;
  @Int64() external int win_behavior;
  @Int64() external int loss_dev_filter;
  @Int64() external int recovery_direction1;
  @Int64() external int recovery_direction2;
  @Int64() external int trigger_mode;
  @Int64() external int trigger_dev2;
  @Int64() external int s2_dev1;
  @Int64() external int s2_dev2;
  @Int64() external int s2_dev3;
  @Double() external double stake;
  @Double() external double take_profit;
  @Double() external double stop_loss;
  @Double() external double martingale_multiplier;
  @Double() external double max_stake;
  @Double() external double max_daily_loss;
}

final class TcTickResult extends Struct {
  @Int64() external int action;
  @Int64() external int error_code;
  @Int64() external int trade_id;
  @Int64() external int digit;
  @Int64() external int direction;
  @Int64() external int barrier;
  @Int64() external int payload_len;
  @Int64() external int t_digit_us;
  @Int64() external int t_trigger_us;
  @Double() external double stake;
}

final class TcState extends Struct {
  @Int64() external int bot_status;
  @Int64() external int fsm_state;
  @Int64() external int public_conn;
  @Int64() external int trade_conn;
  @Int64() external int account_verified;
  @Int64() external int account_real;
  @Int64() external int market;
  @Int64() external int prev_digit;
  @Int64() external int cur_digit;
  @Int64() external int deviation_sign;
  @Int64() external int consec_pos;
  @Int64() external int consec_neg;
  @Int64() external int trigger_status;
  @Int64() external int signal_direction;
  @Int64() external int signal_barrier;
  @Int64() external int recovery_level;
  @Int64() external int martingale_level;
  @Int64() external int wins;
  @Int64() external int losses;
  @Int64() external int total_trades;
  @Int64() external int consec_losses;
  @Int64() external int last_result;
  @Int64() external int last_error;
  @Int64() external int open_contract_id;
  @Int64() external int last_trade_id;
  @Int64() external int needs_reconcile;
  @Int64() external int emergency_latched;
  @Int64() external int recent_count;
  @Int64() external int record_seq;
  @Int64() external int last_tick_epoch;
  @Int64() external int lat_tick_to_trigger_us;
  @Int64() external int lat_trigger_to_send_us;
  @Int64() external int lat_send_to_ack_us;
  @Int64() external int lat_ack_to_open_us;
  @Int64() external int lat_total_us;
  @Int64() external int loss_filter_on;
  @Int64() external int restricted_dev2;
  @Int64() external int filter_rejects;
  @Int64() external int s1_on;
  @Int64() external int s2_on;
  @Int64() external int s2_idx;
  @Int64() external int s2_wins;
  @Int64() external int s2_losses;
  @Int64() external int trade_owner;
  @Int64() external int s2_started;
  @Int64() external int s2_pending;
  @Array(16) external Array<Int64> recent;
  @Double() external double average;
  @Double() external double deviation;
  @Double() external double current_stake;
  @Double() external double balance;
  @Double() external double session_pnl;
  @Double() external double daily_pnl;
  @Double() external double last_profit;
  @Double() external double stats_pnl;
}

final class TcRecord extends Struct {
  @Int64() external int trade_id;
  @Int64() external int tick_epoch;
  @Int64() external int market;
  @Int64() external int account_real;
  @Int64() external int prev_digit;
  @Int64() external int cur_digit;
  @Int64() external int deviation_sign;
  @Int64() external int consecutive_seq;
  @Int64() external int trigger_digit;
  @Int64() external int direction;
  @Int64() external int barrier;
  @Int64() external int recovery_level;
  @Int64() external int martingale_level;
  @Int64() external int result;
  @Int64() external int contract_id;
  @Int64() external int t_tick_rx_us;
  @Int64() external int t_digit_us;
  @Int64() external int t_trigger_us;
  @Int64() external int t_request_us;
  @Int64() external int t_ack_us;
  @Int64() external int t_open_us;
  @Double() external double average;
  @Double() external double deviation;
  @Double() external double stake;
  @Double() external double profit;
}
