#!/usr/bin/env python3
"""Single source of truth for the C<->Dart FFI structs. Every field is 8 bytes (int64/double),
so C and Dart layouts cannot drift. Run: python3 tools/gen_structs.py"""
import os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
S = {
 "TcConfig": (["market","direction","initial_barrier","recovery_barrier1","recovery_barrier2","trigger_digit",
   "consecutive_count","deviation_direction","martingale_enabled","martingale_max_steps",
   "max_consecutive_losses","win_behavior","loss_dev_filter","recovery_direction1","recovery_direction2","trigger_mode","trigger_dev2","s2_dev1","s2_dev2","s2_dev3"],
  ["stake","take_profit","stop_loss","martingale_multiplier","max_stake","max_daily_loss"], []),
 "TcTickResult": (["action","error_code","trade_id","digit","direction","barrier","payload_len","t_digit_us","t_trigger_us"],
  ["stake"], []),
 "TcState": (["bot_status","fsm_state","public_conn","trade_conn","account_verified","account_real","market",
   "prev_digit","cur_digit","deviation_sign","consec_pos","consec_neg","trigger_status","signal_direction",
   "signal_barrier","recovery_level","martingale_level","wins","losses","total_trades","consec_losses",
   "last_result","last_error","open_contract_id","last_trade_id","needs_reconcile","emergency_latched",
   "recent_count","record_seq","last_tick_epoch","lat_tick_to_trigger_us","lat_trigger_to_send_us",
   "lat_send_to_ack_us","lat_ack_to_open_us","lat_total_us","loss_filter_on","restricted_dev2","filter_rejects","s1_on","s2_on","s2_idx","s2_wins","s2_losses","trade_owner","s2_started","s2_pending"],
  ["average","deviation","current_stake","balance","session_pnl","daily_pnl","last_profit","stats_pnl"], [("recent",16)]),
 "TcRecord": (["trade_id","tick_epoch","market","account_real","prev_digit","cur_digit","deviation_sign",
   "consecutive_seq","trigger_digit","direction","barrier","recovery_level","martingale_level","result",
   "contract_id","t_tick_rx_us","t_digit_us","t_trigger_us","t_request_us","t_ack_us","t_open_us"],
  ["average","deviation","stake","profit"], []),
}
c = ["// GENERATED by tools/gen_structs.py - do not edit.", "#pragma once", "#include <stdint.h>",
     "#ifdef __cplusplus", 'extern "C" {', "#endif"]
d = ["// GENERATED by tools/gen_structs.py - do not edit.", "// ignore_for_file: non_constant_identifier_names",
     "import 'dart:ffi';", ""]
for n,(ii,dd,aa) in S.items():
    c.append("typedef struct %s {" % n)
    d.append("final class %s extends Struct {" % n)
    for f in ii:
        c.append("  int64_t %s;" % f); d.append("  @Int64() external int %s;" % f)
    for f,k in aa:
        c.append("  int64_t %s[%d];" % (f,k)); d.append("  @Array(%d) external Array<Int64> %s;" % (k,f))
    for f in dd:
        c.append("  double %s;" % f); d.append("  @Double() external double %s;" % f)
    c.append("} %s;" % n); d.append("}\n")
c += ["#ifdef __cplusplus","}","#endif",""]
open(os.path.join(ROOT,"native/cpp/engine/tc_structs.h"),"w").write("\n".join(c))
open(os.path.join(ROOT,"lib/ffi/tc_structs.dart"),"w").write("\n".join(d))
print("ok")
